# Generated by Django 3.2.9 on 2021-11-05 12:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0002_auto_20211105_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='income',
            name='Date',
        ),
        migrations.AddField(
            model_name='expenses',
            name='Date_expense',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='Date_income',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 11, 5, 12, 51, 9, 701908, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
