# Generated by Django 3.2.9 on 2021-11-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ET', '0003_auto_20211105_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
